services:

  dockerflow:
    image: dockerflow
    restart: unless-stopped
#    volumes:
#      - /flow-library/node_modules # prevent them being overwritten by the above
#      - .:/flow-library
    ports:
      - "8008:8008"
      - "5858:5858"
    links:
      - mongo
    environment:
      NODE_ENV: development
  mongo:
    image: mongo
    volumes:
      - /data/flow/moongodb:/data/db

